/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: StrykerDoesAnimation (https://sketchfab.com/strykerdoesgames)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dancing-stormtrooper-12bd08d66fe04a84be446e583d6663ac
Title: DANCING STORMTROOPER
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useLayoutEffect, useRef } from "react";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/demo-2025-threejs-media-recorder/dancing_stormtrooper.glb"
  );
  const { actions } = useAnimations(animations, group);

  useLayoutEffect(() => {
    const anim = actions["mixamo.com"];
    anim?.play();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="f8ce42897676455090b6ff376356f84cfbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Stormtroopermat}
                    skeleton={nodes.Object_7.skeleton}
                    castShadow
                  />
                  <group name="Object_6" />
                  <group name="Stormtrooper" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}
