name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Build project
        run: |
          yarn
          yarn build

  emit:
    name: Emit
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Emit repository_dispatch event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.FARAZ_PORTFOLIO_PAT }}
          repository: Faraz-Portfolio/demos.farazzshaikh.com
          event-type: update-submodules
